#!/bin/bash
# ============================================================================
# Claude Efficiency Configuration Setup
# ============================================================================
# Quick installation script for Claude Code efficiency configuration
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR"

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     Claude Code Efficiency Configuration Setup               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Step 1: Copy .claudeignore to workspace root (if not exists)
echo "📁 Step 1: Setting up .claudeignore..."
if [ ! -f "../.claudeignore" ]; then
    cp "$CONFIG_DIR/.claudeignore" "../.claudeignore"
    echo "   ✓ Created .claudeignore in workspace root"
else
    echo "   ⚠ .claudeignore already exists, skipping"
fi

# Step 2: Copy workspace.env to workspace root (if not exists)
echo ""
echo "⚙️  Step 2: Setting up workspace.env..."
if [ ! -f "../workspace.env" ]; then
    cp "$CONFIG_DIR/workspace.env" "../workspace.env"
    echo "   ✓ Created workspace.env in workspace root"
    echo "   💡 Edit ../workspace.env to customize settings"
else
    echo "   ⚠ workspace.env already exists, skipping"
    echo "   💡 To reset: rm ../workspace.env && ./setup.sh"
fi

# Step 3: Create loader script in workspace root
echo ""
echo "🔧 Step 3: Creating loader script..."
cat > "../claude-load.sh" << 'LOADER_EOF'
#!/bin/bash
# ============================================================================
# Claude Workspace Configuration Loader
# ============================================================================
# Auto-generated by setup.sh
# ============================================================================

WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$WORKSPACE_ROOT/claude-efficiency-config"
WORKSPACE_ENV="$WORKSPACE_ROOT/workspace.env"

# Check if workspace.env exists
if [ ! -f "$WORKSPACE_ENV" ]; then
    echo "❌ workspace.env not found at: $WORKSPACE_ENV"
    echo "💡 Run: cd claude-efficiency-config && ./setup.sh"
    return 1
fi

# Load environment variables
echo "📥 Loading Claude configuration from: $WORKSPACE_ENV"
export $(cat "$WORKSPACE_ENV" | grep -v '^#' | grep -v '^$' | xargs)

# Create smart command aliases
create_aliases() {
    local default_model="${CLAUDE_DEFAULT_MODEL:-haiku}"
    local file_model="${CLAUDE_FILE_OPS_MODEL:-haiku}"
    local debug_model="${CLAUDE_DEBUG_MODEL:-sonnet}"
    local design_model="${CLAUDE_DESIGN_MODEL:-opus}"

    # Model shortcuts
    alias ch='claude --model haiku'
    alias cs='claude --model sonnet'
    alias co='claude --model opus'
    alias c="claude --model $default_model"

    # Task-specific shortcuts
    alias cread="claude --model $file_model"
    alias cdebug="claude --model $debug_model"
    alias cdesign="claude --model $design_model"

    # Common operations
    alias ctest='claude --model haiku "Run all tests and report results"'
    alias cfix='claude --model haiku "Fix syntax errors and linting issues"'
    alias cfmt='claude --model haiku "Format all code files"'
    alias clint='claude --model haiku "Run linter and fix issues"'

    # Search helpers
    if [ "$CLAUDE_GREP_FIRST" = "true" ]; then
        alias cfind='claude --model haiku "Use Grep to search, then Read top matches for"'
    fi

    # Utilities
    alias ccost='claude /cost'
    alias cclear='claude /clear'
    alias cstatus='show_claude_config'

    echo "✅ Claude aliases created"
}

# Show current configuration
show_claude_config() {
    echo ""
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║           CLAUDE WORKSPACE CONFIGURATION                  ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo ""
    echo "📍 Config file: $WORKSPACE_ENV"
    echo ""
    echo "🤖 Model Settings:"
    echo "   Default:     ${CLAUDE_DEFAULT_MODEL:-haiku}"
    echo "   File Ops:    ${CLAUDE_FILE_OPS_MODEL:-haiku}"
    echo "   Debug:       ${CLAUDE_DEBUG_MODEL:-sonnet}"
    echo "   Design:      ${CLAUDE_DESIGN_MODEL:-opus}"
    echo ""
    echo "⚡ Optimizations:"
    echo "   Grep First:       ${CLAUDE_GREP_FIRST:-false}"
    echo "   Use Glob:         ${CLAUDE_USE_GLOB:-false}"
    echo "   Batch Files:      ${CLAUDE_BATCH_FILES:-false}"
    echo "   Max Files/Req:    ${CLAUDE_MAX_FILES_PER_REQUEST:-5}"
    echo "   Response Style:   ${CLAUDE_RESPONSE_STYLE:-balanced}"
    echo ""
    echo "🎯 Project Info:"
    echo "   Type:       ${PROJECT_TYPE:-unknown}"
    echo "   Language:   ${PROJECT_LANGUAGE:-unknown}"
    echo "   Framework:  ${PROJECT_FRAMEWORK:-unknown}"
    echo ""
    echo "💡 Available commands:"
    echo "   ch  - Use Haiku (cheap)"
    echo "   cs  - Use Sonnet (balanced)"
    echo "   co  - Use Opus (powerful)"
    echo "   c   - Use default model"
    echo ""
    echo "   ctest  - Run tests"
    echo "   cfix   - Fix errors"
    echo "   cfmt   - Format code"
    echo "   ccost  - Check costs"
    echo "   cclear - Clear context"
    echo ""
    echo "📚 Documentation:"
    echo "   cat $CONFIG_DIR/README.md"
    echo "   cat $CONFIG_DIR/QUICK_REFERENCE.md"
    echo ""
}

# Initialize
create_aliases

# Show welcome message
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  ✨ Claude Code Configuration Loaded                      ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "💡 Type 'cstatus' to see current settings"
echo "📖 Quick reference: cat claude-efficiency-config/QUICK_REFERENCE.md"
echo ""

# Export functions
export -f show_claude_config
LOADER_EOF

chmod +x "../claude-load.sh"
echo "   ✓ Created claude-load.sh in workspace root"

# Step 4: Add to shell config (optional)
echo ""
echo "🚀 Step 4: Shell integration (optional)..."
echo "   To auto-load on terminal start, add to your shell config:"
echo ""
echo "   For zsh (~/.zshrc):"
echo "   echo 'source \"$WORKSPACE_ROOT/claude-load.sh\"' >> ~/.zshrc"
echo ""
echo "   For bash (~/.bashrc):"
echo "   echo 'source \"$WORKSPACE_ROOT/claude-load.sh\"' >> ~/.bashrc"
echo ""
read -p "   Add to ~/.zshrc now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if ! grep -q "claude-load.sh" ~/.zshrc 2>/dev/null; then
        echo "" >> ~/.zshrc
        echo "# Claude Code Efficiency Configuration" >> ~/.zshrc
        echo "source \"$WORKSPACE_ROOT/claude-load.sh\"" >> ~/.zshrc
        echo "   ✓ Added to ~/.zshrc"
        echo "   💡 Restart terminal or run: source ~/.zshrc"
    else
        echo "   ⚠ Already exists in ~/.zshrc"
    fi
else
    echo "   ⏭ Skipped shell integration"
fi

# Step 5: Summary
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  ✅ Setup Complete!                                       ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📂 Files created:"
echo "   ├── workspace.env         (main configuration)"
echo "   ├── claude-load.sh        (loader script)"
echo "   └── .claudeignore         (file exclusions)"
echo ""
echo "🚀 Quick Start:"
echo "   1. Load config:    source claude-load.sh"
echo "   2. Check status:   cstatus"
echo "   3. Try it:         ch 'read package.json'"
echo ""
echo "📖 Documentation:"
echo "   cd claude-efficiency-config"
echo "   cat README.md              (overview)"
echo "   cat GET_STARTED.md         (quick start guide)"
echo "   cat QUICK_REFERENCE.md     (cheat sheet)"
echo ""
echo "⚙️  Customize:"
echo "   Edit workspace.env to change settings"
echo ""
echo "💡 Next: Run 'source ../claude-load.sh' to activate!"
echo ""
